### ISSUE TITLE
Translation submitted but not appearing in voting

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#281]
This issue concerns http://litpap.info/editor/publications/588

We submitted a translation via the editor, but it does not appear in voting. IOW, it has disappeared.

**Comment by Edelweiss** [comment]
Should work now with the new board that can handle translations.

**Comment by Edelweiss** [comment]
SQL to set up dummy boards for Webrick development environment

```sql
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
INSERT INTO "users" VALUES(1,'dummy','2011-11-17 14:46:37','2011-11-17 14:46:37','f',NULL,'t','t',NULL,'dummy@googlemail.com',NULL,'Dummy User','t','t');

INSERT INTO "boards" VALUES(1,'DCLP_Editorial_Board',NULL,NULL,'2017-11-22 15:22:57.688000','2017-11-22 15:56:37.032000',NULL,'---
- DCLPMetaIdentifier
- DCLPTextIdentifier
',1,'DCLP Text and Meta',NULL);
INSERT INTO "boards" VALUES(2,'DCLP_Translation_Board',NULL,NULL,'2018-01-17 13:21:52.756000','2018-01-17 13:23:32.638000',NULL,'---
- HGVTransIdentifier
',2,'DCLP Translation',NULL);

INSERT INTO "boards_users" VALUES(1,1,'2017-11-22 15:23:14.254000','2017-11-22 15:23:14.254000');
INSERT INTO "boards_users" VALUES(2,1,'2018-01-17 13:22:09.260000','2018-01-17 13:22:09.260000');

INSERT INTO "decrees" VALUES(1,'approve',1,'Accept-Straight-to-Finalization',1,'2017-11-22 15:56:37.018000','2017-11-22 15:56:37.018000','count');
INSERT INTO "decrees" VALUES(2,'approve',1,'Accept-Straight-to-Finalization',2,'2018-01-17 13:23:32.630000','2018-01-17 13:23:32.630000','count');

COMMIT;
```

**Comment by jcowey** [comment]
Tested by Rodney. Fine. He could and did rename the translation, but he did not finalize it, because I asked him to hold off. We still do not know where the translations are going to live: alongside hgvtrans or as separate dclptrans.
