### ISSUE TITLE
some editions referencing journal articles are incompletely rendered in HTML 

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#31]
From @rogerbagnall via email:

> Picking one at random (https://dclp.github.io/dclpxsltbox/output/dclp/62/61438.html), I'm led to wonder if the 2009 date of the "reference edition" (which has no place of publication, as a book should) and the ZPE article is just a coincidence; or is the reference edition in the ZPE article?

**Comment by paregorios** [comment]
putting on the backlog pending resolution of #32

**Comment by paregorios** [comment]
This ticket is now about the specific problem spotted by @rogerbagnall noted at the top of this ticket. I'll restate and annotate here:

Consider [TM 61438](https://github.com/DCLP/idp.data/blob/master/DCLP/62/61438.xml). Therein we find the following XML:

```xml
<bibl type="reference" subtype="partial">
  <ptr target="http://papyri.info/biblio/83747"/>
  <!--ignore - start, i.e. SoSOL users may not edit this-->
  <title type="main" level="a">Lukrez in Herkulaneum? - Beitrag zu einer Edition von PHerc. 395</title>
  <author n="1">
     <surname>Beer</surname>
     <forename>Beate</forename>
  </author>
  <date>2009</date>
  <!--ignore - stop-->
</bibl>
```

The corresponding bibliographic data is to be found in https://github.com/DCLP/idp.data/blob/master/Biblio/84/83747.xml:

```xml
<bibl xmlns="http://www.tei-c.org/ns/1.0"
      xml:id="b83747"
      type="article"
      subtype="journal">
   <title type="main" level="a">Lukrez in Herkulaneum? - Beitrag zu einer Edition von PHerc. 395</title>
   <author n="1">
      <surname>Beer</surname>
      <forename>Beate</forename>
   </author>
   <date>2009</date>
   <biblScope type="pp">71-82</biblScope>
   <relatedItem type="appearsIn">
      <bibl>
         <ptr target="http://papyri.info/biblio/511"/>
         <!--ignore - start, i.e. SoSOL users may not edit this-->
         <title level="j" type="short-BP">ZPE</title>
         <!--ignore - stop-->
      </bibl>
   </relatedItem>
   <biblScope type="issue">168</biblScope>
   <idno type="pi">83747</idno>
   <idno type="herc-id">313</idno>
</bibl>
```

But [the output that results from the XSL transform](http://dclp.github.io/dclpxsltbox/output/dclp/62/61438.html) does not reflect the full details:

![screen shot 2017-07-19 at 4 47 05 pm](https://user-images.githubusercontent.com/263285/28391041-fb9c9684-6ca1-11e7-8ee4-a1f92d3f5a8a.png)

It looks as if the ```<ptr>``` reference to the biblio XML is not getting processed, or the target record is not understood by the XSLT and so is ignored.

One would expect something more like this:

> Beate Beer, "Lukrez in Herkulaneum? - Beitrag zu einer Edition von PHerc. 395," *Zeitschrift fur Papyrologie und Epigraphik,* 168 (2009), pp. 71-82.

**Comment by paregorios** [comment]
I've just retitled this ticket to indicate the (apparent) fact that there are other examples of this problem. I'm pulling one of them in from #285, which I intend to close as a duplicate for this one.

Consider the principal edition for TM 217929:

```xml
<div type="bibliography" subtype="principalEdition">
    <listBibl>
        <bibl type="publication" subtype="principal">
    <!-- ignore - start, i.e. SoSOL users may not edit this -->
    <!-- ignore - stop -->
          <ptr target="http://papyri.info/biblio/95345"/>
        </bibl>
    </listBibl>
</div>
```

The corresponding biblio XML is:

```xml
<bibl xmlns="http://www.tei-c.org/ns/1.0" xml:id="b95345" type="article" xml:lang="el" subtype="journal">
  <title level="a" type="main">Ροδιακό όστρακο με ερωτικό επίγραμμα</title>
  <author n="1">
    <forename>Anastasia</forename>
    <surname>Dreliosi-Irakleidou</surname>
  </author>
  <author n="2">
    <forename>Nikos</forename>
    <surname>Litinas</surname>
  </author>
  <date>2009-2011</date>
  <biblScope type="pp" from="135" to="155">135-155</biblScope>
  <note type="illustration">p. 155</note>
  <relatedItem type="appearsIn" n="1">
    <bibl>
      <ptr target="http://papyri.info/biblio/papyri.info/biblio/1270"/>
      <!-- ignore - start, i.e. SoSOL users may not edit this -->
      <!-- ignore - stop -->
    </bibl>
  </relatedItem>
  <biblScope type="issue">10-12</biblScope>
  <idno type="bp">2009-1120</idno>
  <idno type="pi">95345</idno>
</bibl>
```

The HTML output looks like:

![screen shot 2017-07-19 at 5 16 48 pm](https://user-images.githubusercontent.com/263285/28392090-17d27676-6ca6-11e7-8822-8ae1bf749d37.png)

but one would expect something more like:

> Anastasia Dreliosi-Irakleidou and Nikos Litinas, "Ροδιακό όστρακο με ερωτικό επίγραμμα," *Eulimene,* 10-12 (2009-2011), pp. 135-155.

**Comment by paregorios** [comment]
Another ticket arising from this same problem is #279, which I am about to close as duplicate. It was concerned with TM 61352. The solution for the problem has already been spelled out in #279, but @wsalesky has asked a couple of questions of @jcowey, which I will reiterate here so he can answer them:

>1. Should the title found in the t:relatedItem[@type='appearsIn']/t:ptr take precedence over the t:title[@type='short-Checklist']?
>
>Also, in this bibl record: https://github.com/papyri/idp.data/blob/master/Biblio/1/511.xml there are two titles:
>
>1. Does the t:title/@type="short-BP" take precedence over the t:title/@type="main"?
>2. Should t:title/@type="main" be used if there is no short title?

**Comment by paregorios** [comment]
/me to clarify based on conversation earlier today with @jcowey

**Comment by paregorios** [comment]
Restating the remaining deficiencies, using TM 61438 as the example. Here's how the bibliographic portions of the metadata currently render to HTML:

![screen shot 2017-08-17 at 2 46 39 pm](https://user-images.githubusercontent.com/263285/29430694-fac3c91a-835a-11e7-9e55-2c629acdd01f.png)

The first "partial edition" is incomplete and wrongly styled. It should read:

 - Beate Beer, "Lukrez in Herkulaneum? - Beitrag zu einer Edition von PHerc. 395," ZPE 168 (2009), pp. 71-82.

I.e., the following problems are evident:

- The article title is styled as if the item is a book, but the item is an article in a journal. This may be detected by the presence of the ```level="a"``` (article) title. The value inside ```<title level="m">``` should be postfixed with a comma and surrounded with quotation marks in output.
- The title of the journal is missing; it should be picked up out of the bibliographic data record indicated by ```<ptr target="``` and displayed in italics immediately following the article title. 
- Next should come the value of ```<biblScope type="issue">```
- Then the date, surrounded in parentheses and this postfixed with comma
- Finally the value of ```<biblScope type="pp">```, postfixed with a period. 

I suspect that the existing stylesheets have some support for this sort of layout, but for whatever reason they're not understanding when used here that they are dealing with a journal article, rather than a book. It may be as simple as a parameter, or may be a consequence of some definitive component expected by the logic that assumes a single, complete bibliographic entry, instead of a containment reference such as we have here involving ```<relatedItem>```.

Note that in picking the title to use for the containing journal, there may be several options available in the Biblio XML file. The following priorities should be observed:

 - if present, use the value of ```<title level="j" type="short-BP">```
 - otherwise ```<title level="j" type="short">```
 - otherwise ```<title level="j" type="main">```
 - otherwise the first occuring ```<title level="j"```.

**Comment by wsalesky** [comment]
Fixed on branch: https://github.com/papyri/navigator/compare/master...DCLP:issue31

XSLT: `navigator/pn-xslt/metadata-dclp.xsl`
Added missing pi:get-docs() function for partial editions (and other t:bibl elements) to follow refs in t:ptr and t:ref elements. 

XSLT:` navigator/pn-xslt/htm-teibibl.xsl`
Choose journal title to use, based on parameters in the previous comment by @paregorios 

HTML output: 
<img width="1116" alt="screen shot 2017-08-19 at 10 30 23 am" src="https://user-images.githubusercontent.com/1168206/29487569-77ed3c22-84c9-11e7-9353-ac20797c1e76.png">

HTML files changed (partial list only, it is a long list):  
```
	modified:   output/dclp/69/68798.html
	modified:   output/dclp/69/68815.html
	modified:   output/dclp/69/68844.html
	modified:   output/dclp/69/68857.html
	modified:   output/dclp/69/68861.html
	modified:   output/dclp/69/68884.html
	modified:   output/dclp/69/68977.html
	modified:   output/dclp/69/68989.html
	modified:   output/dclp/70/69036.html
	modified:   output/dclp/70/69044.html
	modified:   output/dclp/70/69048.html
	modified:   output/dclp/70/69067.html
	modified:   output/dclp/70/69083.html
	modified:   output/dclp/70/69084.html
	modified:   output/dclp/70/69464.html
	modified:   output/dclp/70/69467.html
	modified:   output/dclp/70/69676.html
	modified:   output/dclp/70/69732.html
	modified:   output/dclp/75/74319.html
	modified:   output/dclp/8/7208.html
	modified:   output/dclp/81/80755.html
	modified:   output/dclp/81/80756.html
	modified:   output/dclp/82/81642.html
	modified:   output/dclp/90/89467.html
	modified:   output/dclp/91/90886.html
	modified:   output/dclp/93/92055.html
	modified:   output/dclp/93/92223.html
	modified:   output/dclp/98/97867.html
	modified:   output/dclp/98/97943.html
```
@paregorios ready for review.

**Comment by paregorios** [comment]
This does indeed fix cases like those found in TM61438, but TM 217929 still shows off [the problem highlighted above](https://github.com/DCLP/dclpxsltbox/issues/31#issuecomment-316536046), so there must be something different about that edge case. 

I'm going to go ahead and merge the working changes we have now into DCLP:navigator master, but I will leave the issue31 branch in case we have a chance to deal with the remaining problem.

**Comment by paregorios** [comment]
The results of transforms with the latest code can be reviewed on http://dclp.github.io/dclpxsltbox/output/dclp/. The next time @m-k-r updates from navigator:master on production and re-runs the transforms and mapping they will also be visible there.

**Comment by paregorios** [comment]
Reassigning to @wsalesky to address apparent remaining edge case ^^^

**Comment by wsalesky** [comment]
@paregorios 
Referencing: http://litpap.info/dclp/217929
After some investigation I see several issues. For the particular case above, I think there is an encoding issue:
`<ptr target="http://papyri.info/biblio/papyri.info/biblio/1270"/>` 

looks like a bad URL to me, shouldn't it be: 

`<ptr target="http://papyri.info/biblio/1270"/>` 

However, even with the correct URL the ptr is not processed because there is a rule in the XSLT (https://github.com/DCLP/navigator/blob/master/pn-xslt/htm-teibibl.xsl#L66) which says, print only the title for Principal Editions: 

```
  <xsl:when test="$biblType = 'principalEdition'">
        <xsl:choose>
          <xsl:when test="descendant::t:title[@type='short-Checklist']"><xsl:apply-templates select="descendant::t:title[@type='short-Checklist'][1]"/><xsl:text> </xsl:text></xsl:when>
          <xsl:otherwise><xsl:apply-templates select="t:title[1]"/><xsl:text> </xsl:text></xsl:otherwise>
        </xsl:choose>
      </xsl:when>

```

Should all t:bibl's be processed the same? If so the output for this edge case would look like this: 

`95345. Anastasia Dreliosi-Irakleidou and Nikos Litinas, "Ροδιακό όστρακο με ερωτικό επίγραμμα," Eulimene, 10-12 (2009-2011), pp. 135-155.`

Also, it looks like the principal edition template is being used in two places: 
in the `<h3>` or title of the page, and in the 'Principal Edition' section of the metadata table. This would change the output in both places.

**Comment by paregorios** [comment]
So it sounds like the principal edition template is being overloaded and we made to split out the functions with two separate (moded? named?) templates. 

For ```<h3>```, we should be outputting only the short title plus the biblScope values that give us volume and number (or the equivalent).

But when processing all the bibliography for the metadata listing, we want a full bibliographic citation, exactly as you've shown it in the comment immediately preceding this one. 

@wsalesky does that provide a path forward?

**Comment by wsalesky** [comment]
@paregorios  thank you for the clarification. I will have something to commit tonight.

**Comment by paregorios** [comment]
NB, I'm fiddling with #325 in https://github.com/DCLP/navigator/compare/master...DCLP:issue325

**Comment by paregorios** [comment]
#325 is resolved and merged back to master

**Comment by wsalesky** [comment]
See latest commit: https://github.com/DCLP/navigator/commit/380ffe7e3d60246343a93a71ac12c2b91aabb32c

Does this contradict https://github.com/DCLP/dclpxsltbox/issues/279? Where the request is to use `t:title[@type='short-Checklist']` should I include special handling for Principal Editions to use the `t:title[@type='short-Checklist']`
