### ISSUE TITLE
Display word division with paragraphos

### ISSUE THREAD

**Issue by HolgerEssler** [DCLP/dclpxsltbox#52]
When there is a paragraphos between two lines, the sign of word division seems to be displayed after the paragraphos instead of the preceeding line.
Example: 
http://dclp.github.io/dclpxsltbox/output/dclp/63/62400.html
Col. 51, lines 13-14:
Displays:
    ἀν]θ̣ρ̣[ώ]
—— -
ποιϲ
Should display:
     ἀν]θ̣ρ̣[ώ-]
——
ποιϲ

**Comment by paregorios** [comment]
This is fixed; viz http://dclp.github.io/dclpxsltbox/output/dclp/63/62400.html. One will note there whitespace between the end of the preceding text and the hyphen; I will be opening a new ticket for this bug. @HolgerEssler please review.

**Comment by HolgerEssler** [comment]
There is still a problem with the position of the hyphen in the case of
supplements:
In the above mentioned example now the display is:
ἀν]θ̣ρ̣[ώ] -, but the hyphen should be inside the bracket (as in the lines
above and below:
ἀν]θ̣ρ̣[ώ-]

**Comment by paregorios** [comment]
@HolgerEssler right, thanks

**Comment by paregorios** [comment]
Un-assigning myself to make this one available for others to work on.

**Comment by wsalesky** [comment]
@paregorios 
Can I get some explanation of the logic that should produce the desired output? 
Here is the XML fragment which currently outputs: 
```
λατ[τε· τοῖς δ' ἀν]θ̣ρ̣[ώ] -
——
ποις [τ]δ(*)[ύτην] κ̣[υριω-]
```

XML (pretty printed for legibility only):
```
<lb n="13" break="no"/>λατ
    <supplied reason="lost">τε·</supplied></w> 
    <w n="1051000000013001" type="supplied" lemma="ὁ">
        <supplied reason="lost">τοῖς</supplied>
    </w> 
    <w n="1051000000013002" type="supplied" lemma="δέ">
        <supplied reason="lost">δ'</supplied>
    </w> 
    <w n="1051000000013003" type="supplied">
        <supplied reason="lost">ἀν</supplied>
        <unclear reason="damage">θ</unclear>
        <unclear reason="damage">ρ</unclear>
        <supplied reason="lost">ώ</supplied>
        <milestone rend="paragraphos" unit="undefined"/>
        <lb n="14" break="no"/>ποις
    </w> 
    <w n="1051000000014001" type="supplied">
        <supplied reason="lost">τ</supplied>
        <choice><corr>α</corr><sic>δ</sic></choice>
        <supplied reason="lost">ύτην</supplied></w> 
    <w n="1051000000014002" type="supplied" lemma="κυριωτάτην">
        <unclear reason="damage">κ</unclear>
        <supplied reason="lost">υριω</supplied>
```

Can you explain why the '-' (denoting a milestone break ) should be in the '[]' which denote  supplied text, as opposed to being after the supplied text?

I can edit the XSLT to supply the correct view, but want to make sure my logic matches expectations. 

Thanks.

**Comment by paregorios** [comment]
@wsalesky the hyphen ('-') is actually meant to have nothing to do with the ```<milestone>```; rather, it's an aid to the reader meant to indicate that the editor thinks there's a word being split by the ```<lb>``` that has a ```break="no"``` attribute on it. The convention is to bind that "keep reading because the word is not done" signal as closely as possible to the characters themselves, even if they are part of an editorial supplement. That's where the papyrologists (as @HolgerEssler above) expect to see it. 

The encoding is a bit counter-intuitive, given that the paragraphos symbol appears between the two lines, but the indicator that a hyphen should be postfixed to the final non-diacritical character in the preceding line appears on the "line beginning" tag (```<lb>```) that follows the ```<milestone>```.

**Comment by wsalesky** [comment]
@paregorios  
So how should `t:milestone` elements within a `t:w` be treated? Should it be treated differently within a t:w then within other elements? Currently the milestone outputs a '-' if 
`following-sibling::node()[not(self::text() and normalize-space(self::text())='')][1]/self::t:lb[@break='no']`. Which is the behavior we are seeing here.  What does the`t:milestone ` indicate here?  (Just trying to understand what the encoding means.)

I suspect I need to change the `t:milestone` handling and the `t:supplied` and want to make sure I understand how they should be treated within `t:w` elements. 
Thanks!

**Comment by paregorios** [comment]
@wsalesky please let me know if I've misread your question and the following is orthogonal to what you need.

We use ```<milestone>``` for any number of different things in papyrological EpiDoc, so I'm hesitant to say more about how we should treat it without qualifying the remarks to the level of a particular ```type``` or ```rend``` value. 

In this particular case, we use ```<milestone rend="paragraphos">``` to indicate a place (i.e., prior to the beginning of a line) at which a "[paragraphos](https://en.wikipedia.org/wiki/Paragraphos)" has been inserted in a text on papyrus by a scribe. An unproblematic example of the EpiDoc encoding might look like this:

```xml
<lb n="18"/>φυλῆς 
<milestone rend="paragraphos" unit="undefined"/>
<lb n="19"/>Αὐρήλιος Μουσῆς ...
```

and the papyrologists would expect to see their usual convention for same in the transformed HTML:

```
φυλῆς 
—— 
Αὐρήλιος Μουσῆς
```

i.e., two em-dashes (or whatever those are) between the two lines of text. 

Some (a minority) of our texts use the ```<w>``` element to set off words. Most of our texts don't, relying simply on the appearance of whitespace to indicate word divisions. But note ```<lb break="no"/>```, which causes any whitespace between it and the immediately previous or immediately following node to be ignored). Either way, the trick is to figure out that you need to add a simple hyphen on the last non-space character of the first line because there's a following ```<lb break="no"/>``` and then put in a line with the two em dashes because there's a following ```<milestone rend="paragraphos">``` (even though it comes in document order **before** the ```<lb>```). So, I would expect to see the following two encoding examples produce the indicated HTML:

No ```<w>``` wrapping:

```xml
<lb n="19"/> ... καὶ τὴν θυγατέρα προσενηνο
<milestone rend="paragraphos" unit="undefined"/>
<lb n="20" break="no"/>χέναι ἑαυτῇ εἰς ...
```

With ```<w>``` wrapping:

```xml
<lb n="19"/> ... <w>καὶ</w> <w>τὴν</w> <w>θυγατέρα</w> <w>προσενηνο
<milestone rend="paragraphos" unit="undefined"/>
<lb n="20" break="no"/>χέναι</w> <w>ἑαυτῇ</w> <w>εἰς</w> ...
```

Expected HTML appearance for either of the above:
```
... καὶ τὴν θυγατέρα προσενηνο-
—— 
χέναι ἑαυτῇ εἰς ..
```

Regardless of the presence or absence of ```<w>```, when a word is (1) split across a line beginning, (2) falls within or contains ```<supplied reason="lost">``` that continues to the end of the first line, and (3) the scribe has inserted a paragraphos before the second line, the expectation of the papyrologist is that: (a) the supplied section is contained within square brackets, (b) the hyphen indicating a word spanning a line appears as the last character **before** the closing square bracket on the first line, and (c) the paragraphos appears between the two lines. Thus:

No ```<w>``` wrapping:

```xml
<lb n="19"/> ... καὶ τὴν θυγατέρα <supplied reason="lost">προσενηνο</supplied>
<milestone rend="paragraphos" unit="undefined"/>
<lb n="20" break="no"/>χέναι ἑαυτῇ εἰς ...
```

With ```<w>``` wrapping:

```xml
<lb n="19"/> ... <w>καὶ</w> <w>τὴν</w> <w>θυγατέρα</w> <w><supplied reason="lost">προσενηνο</supplied>
<milestone rend="paragraphos" unit="undefined"/>
<lb n="20" break="no"/>χέναι</w> <w>ἑαυτῇ</w> <w>εἰς</w> ...
```

Expected HTML appearance for either of the above:
```
... καὶ τὴν θυγατέρα [προσενηνο-]
—— 
χέναι ἑαυτῇ εἰς ..
```

**Comment by wsalesky** [comment]
@paregorios Thanks, I will see what I can do.

**Comment by paregorios** [comment]
@wsalesky I've just noticed that #251 and #151 also address hyphen-placement issues across word breaks, so at least involve the same portion of code ..

**Comment by wsalesky** [comment]
Okay, I think I have this sorted out. 

Stylesheets changed:

1. epidoc-xslt/htm-teimilestone.xsl
2. epidoc-xslt/teig.xsl

A few diff examples:

```
diff --git a/output/dclp/113/112359.html b/output/dclp/113/112359.html
index c445eacbc..bf51ddbdb 100644
--- a/output/dclp/113/112359.html
+++ b/output/dclp/113/112359.html
@@ -128,7 +128,7 @@
                                 <!--0--></a>[- ca.15 -οὐδὲ] ὁ προφήτης;<br id="av-l2">[ἀπεκρίθη αὐτοῖς ὁ Ἰωάν]νης λέγων, Ἐγὼ βα-<br id="av-l3">[πτίζω ὑμᾶς ἐν ὕδατι· μέ]σ̣ος ὑ̣<a href="#to-app-hi01" id="from-app-hi01">(*)</a>μ̣ῶ̣ν ι̣<a href="#to-app-hi02" id="from-app-hi02">(*)</a>-<br id="av-l4">[στηκει]<a href="#to-app-choice01" id="from-app-choice01">(*)</a> [ὃν ὑμεῖς οὐκ οἴδ]α̣τε, ὁ ὀπίσω<br id="av-l5"><span class="linenumber">5</span>[μου ἐρχόμενος, οὗ οὐκ εἰ]μ̣ὶ ἄξιος ἵ<a href="#to-app-hi03" id="from-app-hi03">(*)</a>να̣<br id="av-l6">[λύσω αὐτοῦ τὸν ἱμάντα] τ̣οῦ ὑ<a href="#to-app-hi04" id="from-app-hi04">(*)</a>ποδή-<br id="av-l7">[ματος. ταῦτα ἐν Βηθανί]ᾳ ἐγένετο<br id="av-l7">[15 lines missing]<br id="av-l23"><span class="linenumber">23</span>[- ca.17 -] Ἐφ’ ὃ̣ν ἐ̣ὰν̣ [ἴδῃς]<br id="av-l24">[τὸ πν(εῦμ)α καταβαῖνον κα]ὶ μένον ἐ̣[π’]<br id="av-l25"><span class="linenumber">25</span>[αὐτόν, οὗτός ἐστιν ὁ βαπ]τ̣[ίζων ἐν]<br id="av-l26">[πν(εύματ)ι ἁγίῳ. κἀγὼ ἑώρακα,] κ̣αὶ μεμ̣[αρ-]<br id="av-l27">[τύρηκα ὅτι οὗτός ἐστ]ι̣ν ὁ υ<a href="#to-app-hi05" id="from-app-hi05">(*)</a>ἱὸς ὁ̣ 
                           </div>  <span class="textpartnumber" id="abr">r</span><br>  
                           <div class="textpart"><a id="ar-l28">
                                 <!--0--></a>τ̣ο̣ῦ̣ θ(εο)ῦ. τῇ̣ [ἐπαύριον εἱστήκει ὁ<a href="#to-app-app01" id="from-app-app01">(*)</a> Ἰωάν] -<br>——<brἸωάν-] <br>——<br id="ar-l29">νης καὶ̣ ἐ̣[κ τῶν μαθητῶν αὐτοῦ δύο,]<br id="ar-l30"><span class="linenumber">30</span>καὶ̣ ἐ̣μ̣βλέ̣[ψας τῷ Ἰη(σο)ῦ περιπατοῦντι]<br id="ar-l31">λέγει, Ἴ<a href="#to-app-hi06" id="from-app-hi06">(*)</a>δε ὁ [ἀμνὸς τοῦ θ(εο)ῦ. καὶ ἀκούσαν-]<br id="ar-l32">[τ]ε̣ς οἱ δύο μ̣[αθηταὶ αὐτοῦ λαλοῦντος]<br id="ar-l33">ἠκολούθη[σαν τῷ Ἰη(σο)ῦ στραφεὶς δὲ ὁ]<br id="ar-l34">Ἰη(σοῦ)ς καὶ θεα̣[σάμενος- ca.12 -]<br id="ar-l34">[14 lines missing]<br id="ar-l49"><span class="linenumber">49</span>[- ca.23 -ἑρμη-]<br id="ar-l50"><span class="linenumber">50</span>ν̣εύεται Π̣[έτρος. τῇ ἐπαύριον ἠθέλη-]<br id="ar-l51">[σ]εν ἐ̣ξελ[θεῖν εἰς τὴν Γαλιλαίαν, καὶ]<br id="ar-l52">[εὑρίσ]κ̣ε̣[ι Φίλιππον. καὶ λέγει αὐτῷ ὁ Ἰη(σοῦ)ς,]<br id="ar-l53">[ἀ]κολούθ[ει μοι. ἦν δὲ ὁ Φίλιππος ἀπὸ]<br id="ar-l54">Βηθ’σαϊ<a href="#to-app-hi07" id="from-app-hi07">(*)</a>δ̣[ά- ca.20 -] 
                           </div>  
                           <h2>Apparatus</h2>
                           <div id="apparatus"><br><a id="to-app-hi01" href="#from-app-hi01">^</a> v.3. <span>ϋμ̣ῶ̣ν papyrus</span><br><a id="to-app-choice01" href="#from-app-choice01">^</a> v.3-4. <span title="Scribe wrote ι̣|[στηκει], for which read εἱ|στήκει"> l. εἱ|στήκει</span> : <span>|[στηκει]ϊ papyrus</span><br><a id="to-app-hi03" href="#from-app-hi03">^</a> v.5. <span>ϊνα̣ papyrus</span><br><a id="to-app-hi04" href="#from-app-hi04">^</a> v.6. <span>ϋποδη papyrus</span><br><a id="to-app-hi05" href="#from-app-hi05">^</a> v.27. <span>ϋιοσ papyrus</span><br><a id="to-app-app01" href="#from-app-app01">^</a> r.28. <span title="Scribe wrote εἱστήκει ὁ or εἱστήκει"> or εἱστήκει</span><br><a id="to-app-hi06" href="#from-app-hi06">^</a> r.31. <span>ϊδε papyrus</span><br><a id="to-app-hi07" href="#from-app-hi07">^</a> r.54. <span>βηθ’σαϊδ̣[ά- ca.20 -] papyrus</span></div>

```

```
diff --git a/output/dclp/114/113270.html b/output/dclp/114/113270.html
index da89b0492..11bf56ee5 100644
--- a/output/dclp/114/113270.html
+++ b/output/dclp/114/113270.html
@@ -123,7 +123,7 @@
                        </h2>
                        <div id="edition" lang="grc">  <span class="textpartnumber" id="ab1">fragment 1</span><br>  <span class="textpartnumber" id="textpart-ab1-i">column i</span><br>  
                           <div class="textpart"><a id="a1-i-l1">
                                 <!--0--></a><span title="number: 8"><span class="supraline" title="line above">η</span></span>· γ̣ένος, φύσιν, ἀγωγήν, ἡλικίαν, τ̣ύ̣χ̣[ην, πρά-]<br id="a1-i-l2">ξε̣ις̣, π̣άθος, διάθεσιν̣. οἷον ὁ πατρο̣τύπ̣[της χειρο-]<br id="a1-i-l3">κ̣οπείσθω. ∶ γένος μὲ̣ν π̣ότερον<a href="#to-app-subst01" id="from-app-subst01">(*)</a> θετ[ὸς ἢ γνή] -<br>——<brγνή-] <br>——<br id="a1-i-l4">σι̣ο̣ς̣. ∶ φύσιν δὲ ἄρρην ἢ θήλεια. ∶ ἀ̣[γωγὴν] <br>——<br id="a1-i-l5"><span class="linenumber">5</span>π̣ό̣τ̣ε̣ρον ὑβριστὴς τὰ πάντα ἢ κἂν̣ [- ca.5 -]<br id="a1-i-l6">[&nbsp;&nbsp;̣]&nbsp;&nbsp;̣<a href="#to-app-app01" id="from-app-app01">(*)</a> μ̣έ̣τριος. ∶ ἡλικίαν παῖς ἢ μιράκ̣ιο̣[ν.]<a href="#to-app-choice01" id="from-app-choice01">(*)</a>[τύ-]<br id="a1-i-l7">χη̣ν̣ ἰ̣<a href="#to-app-hi02" id="from-app-hi02">(*)</a>διώτης μόνον ἢ κἂν ἄρχων̣. ∶ [πρά] -<br>——<br[πρά-] <br>——<br id="a1-i-l8">ξ̣[ε]ι̣ς̣ ε̣ἰ̣ χει̣ροκοπηθήσεται κἂν ᾖ ἀρι̣σ̣τ̣[εὺς ἢ<a href="#to-app-app02" id="from-app-app02">(*)</a>]<br id="a1-i-l9">τ̣υ̣ρ̣α̣ννοκτόνος. ∶ πάθος κἂν πεπηρ[ωμέ] -<br>——<brπεπηρ[ωμέ-] <br>——<br id="a1-i-l10"><span class="linenumber">10</span>ν̣ο̣ς. διάθεσιν κἂν εὔνους ἐξ ἀρχ[ῆς. τὸ] <br>——<br id="a1-i-l11">δὲ̣ πρ̣ᾶγμ̣α̣ διαιρεῖται εἰς μέρη <span title="number: 8"><span class="supraline" title="line above">η</span></span>· πρό[σωπον,]<br id="a1-i-l12">αἰτίαν, τόπον, χρό̣νον, τρόπον, τὰ π̣ρὸ [τοῦ πρά-]<br id="a1-i-l13">γ̣μ̣α̣τος, τὰ ἐν τῷ πράγματι, τὰ μετὰ̣ τ[ὸ πρᾶ-]<br id="a1-i-l14">γ̣μ̣α̣. ∶ οἷον πρόσωπον εἰ καὶ ὁ τὴν μ̣η̣[τέρα] <br>——<br id="a1-i-l15"><span class="linenumber">15</span>τυ̣πτήσας χειροκοπηθήσεται̣. ∶ αἰτ̣[ίαν κἂν] <br>——<br id="a1-i-l16">μ̣α̣ινόμενος ἢ με̣θύων. ∶ τ̣όπ̣ον π̣[ότερον]<a href="#to-app-app03" id="from-app-app03">(*)</a> [ἐν] <br>——<br id="a1-i-l17">ἀ̣γ̣ρ̣ῷ ἢ ἐπ’ ἀγορᾶς ἢ̣ ἐπ’ ἰ<a href="#to-app-hi04" id="from-app-hi04">(*)</a>δίας οἰκίας. ∶ [χρό] -<br>——<br[χρό-] <br>——<br id="a1-i-l18">ν̣ο̣ν κἂν πρὸ πολλοῦ ἢ παραχρῆμα. [&lt;τρόπον&gt; πότε-]<br id="a1-i-l19">ρ̣ο̣ν ταῖς χ̣ερσὶν ἢ ξύλῳ. ∶ τὰ πρὸ τοῦ̣ [πρά] -<br>——<br[πρά-] <br>——<br id="a1-i-l20"><span class="linenumber">20</span>γματος κἂν προακούσας \κακῶς/ ἢ προϋ̣[βρισ-]<br id="a1-i-l21">θ̣ε̣ίς<a href="#to-app-subst02" id="from-app-subst02">(*)</a>. ∶ τὰ ἐν τῷ πρά̣γματι ∶ εἰ τύπτ[ων μὴ τρώ] -<br>——<brτρώ-] <br>——<br id="a1-i-l22">σ̣ε̣ι̣ε. ∶ τὰ μετὰ τὸ πρᾶγμα κἂν ἐκ̣ [τῶν] <br>——<br id="a1-i-l23">π̣[λ]ηγῶν ἀποθάνῃ &lt;ἢ&gt; εἰ καὶ̣ το̣ῦ πατρ̣ὸ̣[ς μὴ βου-]<br id="a1-i-l24">λ[ο]μ̣ένου χειροκοπηθήσ̣εται. ταῦτ[α μὲν δὴ]<br id="a1-i-l25"><span class="linenumber">25</span>πάν̣τα ἀσαφῆ καὶ ἄδη̣λ̣α̣. ∶ παράνομο̣[ς δὲ ὅταν<a href="#to-app-app05" id="from-app-app05">(*)</a>] <br>——<br id="a1-i-l26">[ἐν]αντίος ᾖ ὁ νῦν εἰσηγούμενος τοῖ̣[ς ἤδη<a href="#to-app-app06" id="from-app-app06">(*)</a>]<br id="a1-i-l27">[κ]ε̣κυρωμένοις, ∶ ἄδικος δὲ ὅτα̣ν̣ μ̣&nbsp;&nbsp;̣[ -ca.?- ] 
                           </div>  <span class="textpartnumber" id="textpart-ab1-ii">column ii</span><br>  
                           <div class="textpart"><a id="a1-ii-l1">
                                 <!--0--></a>[1 line missing]<br id="a1-ii-l2"><span class="linenumber">2</span>[1 line missing]<a href="#to-app-app07" id="from-app-app07">(*)</a><br id="a1-ii-l2">[ca.22 lines missing]<br id="a1-ii-l25"><span class="linenumber">25</span>[1 line missing]<br id="a1-ii-l26"><span class="linenumber">26</span>[1 line missing]<br id="a1-ii-l27"><span class="linenumber">27</span>[1 line missing]<a href="#to-app-app08" id="from-app-app08">(*)</a>  
```

```
diff --git a/output/dclp/120/119313.html b/output/dclp/120/119313.html
index d7c3f7b53..d4c9933d9 100644
--- a/output/dclp/120/119313.html
+++ b/output/dclp/120/119313.html
@@ -153,7 +153,7 @@
                                 <!--0--></a>[νύξας δὲ] τ̣ὴν<br id="a3b-ii-l2">[πλευρὰν α]ὐτοῦ<br id="a3b-ii-l3">[ἤγειρεν] λ̣έγων<br id="a3b-ii-l4">[ἀνάστα ἐ]ν τά-<br id="a3b-ii-l5"><span class="linenumber">5</span>[χει. καὶ ἰδ]οὺ αἱ ἁ-<br id="a3b-ii-l6">[λύσεις ἐ]κ̣ τῶν<br id="a3b-ii-l7">[χειρῶν αὐ]τ̣ο̣ῦ<br id="a3b-ii-l8">[ἐξέπεσα]ν ((mese-stigme)) εἶ-<br id="a3b-ii-l9">[πεν δὲ ὁ] ἄ̣γγελος<br id="a3b-ii-l10"><span class="linenumber">10</span>[τῷ Π]έτρῳ ((mese-stigme)) <br id="a3b-ii-l11">[ζῶσαι κ]α̣ὶ̣ ὑπό-<br id="a3b-ii-l12">[δησαι τὰ] ὑ̣πο-<br id="a3b-ii-l13">[δήματά σ]ου ((mese-stigme)) κ(αὶ)<br id="a3b-ii-l14">[περιβαλ]ο̣ῦ τ[ὸ]<br id="a3b-ii-l15"><span class="linenumber">15</span>[ἱμάτιό]ν̣ σ̣ου ((mese-stigme)) <br id="a3b-ii-l16">[καὶ λαβό]μ̣ενος<br id="a3b-ii-l17">[τὸν Πέτρον] προ-<br id="a3b-ii-l18">[ήγαγεν ἔ]ξω εἰ-<br id="a3b-ii-l19">πὼν̣, [ἀκ]ο̣λού-<br id="a3b-ii-l20"><span class="linenumber">20</span>θει μ[οι. ὁ] δὲ Πέ-<br id="a3b-ii-l21">τρος ἠ[κο]λ̣ού-<br id="a3b-ii-l22">θει μὴ̣ [εἰ]δ̣ὼς<br id="a3b-ii-l23">εἰ̣ ἀ̣λ̣η[θὲ]ς ἐστὶ 
                           </div>  <span class="textpartnumber" id="ab4a">folio 4a</span><br>  <span class="textpartnumber" id="textpart-ab4a-i">column i</span><br>  
                           <div class="textpart"><a id="a4a-i-l6">
                                 <!--0--></a>[5 lines missing]<br id="a4a-i-l6"><span class="linenumber">6</span>&nbsp;&nbsp;̣[ -ca.?- ]<br id="a4a-i-l7">δ̣[ιατηροῦν-]<br id="a4a-i-l8">τες [ἑαυτοὺς εὖ]<br id="a4a-i-l9">πρά[ξετε ἐν ὀ] -<br>——<brὀ-] <br>——<br id="a4a-i-l10"><span class="linenumber">10</span>λίγα̣ις [δὲ ἡμέ-]<br id="a4a-i-l11">ραις ο̣[ -ca.?- ]<br id="a4a-i-l12">δε[ -ca.?- ]<br id="a4a-i-l13">εἰς Ἀν[τιόχειαν]<br id="a4a-i-l14">κ̣αὶ σ̣υν̣[αγαγόν-]<br id="a4a-i-l15"><span class="linenumber">15</span>τ̣ε̣ς̣ τ̣ὸ [πλῆθος ἐπ-]<br id="a4a-i-l16">έδωκ̣[αν τὰ γράμ-]<br id="a4a-i-l17">ματα ο[ -ca.?- ]<br id="a4a-i-l18">&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣ [ -ca.?- ]<br id="a4a-i-l18">[6 lines missing] 
                           </div>  <span class="textpartnumber" id="textpart-ab4a-ii">column ii</span><br>  
                           <div class="textpart"><a id="a4a-ii-l12">
                                 <!--0--></a>[11 lines missing]<br id="a4a-ii-l12"><span class="linenumber">12</span>[&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣]&nbsp;&nbsp;̣&nbsp;&nbsp;̣[ -ca.?- ]<br id="a4a-ii-l13">[αὐτ]ο̣ῦ̣ μ̣ό̣[νος]<br id="a4a-ii-l14">[δὲ] Ἰ<a href="#to-app-hi08" id="from-app-hi08">(*)</a>ο̣ύ̣δ̣α̣ς̣ ἐπ̣ο̣-<br id="a4a-ii-l15"><span class="linenumber">15</span>[ρεύ]θ̣η̣ ὁ̣ δ̣ὲ̣ Παῦ-<br id="a4a-ii-l16">[λο]ς̣ κα̣ὶ Β̣αρ̣να-<br id="a4a-ii-l17">[βᾶ]ς̣ δι̣έ̣τ̣ρ̣ι̣βον<br id="a4a-ii-l18">[ἐν] Ἀντ̣ι̣ο̣χ̣ε̣ί̣ᾳ<br id="a4a-ii-l19">[διδ]ά̣σ̣κο[ντ]ε̣ς<br id="a4a-ii-l20"><span class="linenumber">20</span>[κα]ὶ ε̣ὐ̣α̣γ̣γ̣ελιζ̣ό̣-<br id="a4a-ii-l21">[με]ν̣οι̣ μετὰ κ(αὶ)<br id="a4a-ii-l22">[ἑτ]έρων πολλῶ̣ν̣<br id="a4a-ii-l23">[τὸ]ν̣ λ̣ό̣γ̣ο̣ν̣ τ̣ο̣ῦ<br id="a4a-ii-l24">[κ(υρίο)υ] εἶπεν δε̣ 

```

I don't see any obvious side effects. So I am turning it over to @paregorios for review. 
(Code Changes: svn.code.sf.net/p/epidoc/code/branches/dclp-issue52/example-p5-xslt)

**Comment by paregorios** [comment]
This is resolved with [r2602 on epidoc-xslt](https://sourceforge.net/p/epidoc/code/2602/).
